name: Date Cron
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git commit --allow-empty -m 'Monitoring $(date +'%d.%m.%Y - %H:%M')'
          git push
