name: Date Cron
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name matsyashchik
          git config user.email m_vlad_f@hotmail.com
          git commit --allow-empty -m 'Monitoring $(date +"%d.%m.%Y")'
          git push
